name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 18

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node modules
        run: npm install

      - name: Run TypeScript typechecking
        run: npm run typecheck

      - name: Run lint
        run: npm run lint
